server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    username: root
    password: 123456

  application:
    name: service-provider # 应用名称，注册到eureka后的服务名称
mybatis:
  type-aliases-package: cn.itcast.service.pojo
eureka:
  instance:
    lease-expiration-duration-in-seconds: 10 #过期时间
    lease-renewal-interval-in-seconds: 5 #心跳时间

  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true